import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="./css/output.css" rel="stylesheet" />
        <link href="./css/output.css" rel="stylesheet" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
        <script
          src="https://www.google.com/recaptcha/api.js"
          async
          defer
        ></script>
        <title>join waitlist</title>
        <script src="https://www.google.com/recaptcha/api.js?render=6LdU4G0nAAAAAE1b61LcnLGwJBLuvrjfA2NbYsUR"></script>
      </head>
      <body className="bg-black">
        {children}
        <script src="/js/app.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script nonce="= cspNonce"></script>
      </body>
    </html>
  );
}
